version: '3.8'
services:
  tailscale-mcp:
    build: .
    container_name: tailscale-mcp
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
    restart: unless-stopped